import { Router } from 'express';
import { healthRouter } from './health.routes.js';
import { authRouter } from './auth.routes.js';
import { areaRouter } from './area.routes.js';
import { jobRouter } from './job.routes.js';
import { ofertaRouter } from './oferta.routes.js';
import { leadRouter } from './lead.routes.js';
import { agenteRouter } from './agente.routes.js';
import { secretariaRouter } from './secretaria.routes.js';
import { juridicoRouter } from './juridico.routes.js';
import { tokensRouter } from './tokens.routes.js';
import { gamificacaoRouter } from './gamificacao.routes.js';
import { adsRouter } from './ads.routes.js';
import { adminRouter } from './admin.routes.js';

export const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/areas', areaRouter);
router.use('/jobs', jobRouter);
router.use('/ofertas', ofertaRouter);
router.use('/leads', leadRouter);
router.use('/agente', agenteRouter);
router.use('/secretaria', secretariaRouter);
router.use('/juridico', juridicoRouter);
router.use('/tokens', tokensRouter);
router.use('/gamificacao', gamificacaoRouter);
router.use('/ads', adsRouter);
router.use('/admin', adminRouter);
